package com.example.clean_architectures_simple_project.Gateway.Database

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.room.*

//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


typealias  UserTb = List<Users>
typealias  LiveUsers = LiveData<UserTb>
typealias  MutableLiveUsers = MutableLiveData<UserTb>

@Entity(tableName = "Users")

data class Users(
    val userId: Int,
    val title: String,
    val completed: Boolean
) {
    @PrimaryKey(autoGenerate = false)
    var id: Int = 1
}


@Dao
interface userDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun set(user: Users)

    @Query("select * from Users ")
    fun getUserAll(): LiveUsers

    @Query("select * from Users where id =:id")
    fun getUser(id: Int): UserTb

}