package com.example.clean_architectures_simple_project.Gateway.GatewayImplementor

import android.util.Log
import com.example.clean_architectures_simple_project.Entity.UserGateway
import com.example.clean_architectures_simple_project.Gateway.Database.Users
import com.example.clean_architectures_simple_project.Gateway.withSuspendGateway
//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


class GatewayImplementor : UserGateway {
    override suspend fun getUserAll() = withSuspendGateway {
        internalDatabase.await().userDao().getUserAll();
    }

    override suspend fun setUser(user: Users) = withSuspendGateway {
        internalDatabase.await().userDao().set(user);
    }


    override suspend fun getUserAsync(id: Int) = withSuspendGateway {
        internalServer.await().getUserAsync(id);
    }


}

