package com.example.clean_architectures_simple_project.presentation.core

import android.util.Log
import android.view.View
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch

//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


fun View.with(callback: suspend () -> Unit) = GlobalScope.launch {

    try {
        callback()
    } catch (e: Exception) {
        Error.set(e)
    }


}

