package com.example.clean_architectures_simple_project

import android.app.Application
import com.example.clean_architectures_simple_project.Domain.DomainDependencies
import com.example.clean_architectures_simple_project.Gateway.Database.buildDatabaseAsync
import com.example.clean_architectures_simple_project.Gateway.GatewayDependencies
import com.example.clean_architectures_simple_project.Gateway.GatewayImplementor.GatewayImplementor
import com.example.clean_architectures_simple_project.Gateway.Server.buildServerAsync

//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------

class App : Application() {


    override fun onCreate() {
        super.onCreate()

       // registerActivityLifecycleCallbacks(BaseCustomActivity())
            GatewayDependencies.with(buildDatabaseAsync(this@App), buildServerAsync(this@App));
            DomainDependencies.with(GatewayImplementor());


    }


}
